# Generated by Django 3.0.4 on 2020-03-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200329_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='about',
            field=models.CharField(max_length=1000),
        ),
    ]
